import { useEffect, useState } from 'react'
import { RotateCw } from 'lucide-react'
import toast from 'react-hot-toast'
import LoadingSkeleton from '../components/ui/LoadingSkeleton'
import SalesChart from '../components/features/SalesChart'
import { getInsights, getSales } from '../services/api'

export default function Insights() {
  const [loading, setLoading] = useState(true)
  const [insights, setInsights] = useState(null)
  const [revenueData, setRevenueData] = useState([])
  const [isRegenrating, setIsRegenerating] = useState(false)

  useEffect(() => {
    fetchInsights()
  }, [])

  const fetchInsights = async () => {
    setLoading(true)
    const [insightResult, salesResult] = await Promise.all([getInsights(), getSales()])

    if (insightResult) {
      setInsights(insightResult)
    }

    if (salesResult) {
      // Get last 30 days revenue
      const last30Days = {}
      const today = new Date()
      for (let i = 0; i < 30; i++) {
        const date = new Date(today)
        date.setDate(date.getDate() - i)
        const dateKey = date.toISOString().split('T')[0]
        last30Days[dateKey] = 0
      }

      salesResult.forEach((sale) => {
        const saleDate = new Date(sale.sale_date).toISOString().split('T')[0]
        if (last30Days.hasOwnProperty(saleDate)) {
          last30Days[saleDate] += parseFloat(sale.sale_amount || 0)
        }
      })

      const chartData = Object.entries(last30Days)
        .reverse()
        .map(([date, total]) => ({
          label: new Date(date).toLocaleDateString('en-IN', { month: 'short', day: 'numeric' }),
          value: Math.round(total),
        }))

      setRevenueData(chartData)
    }

    setLoading(false)
  }

  const handleRegenerate = async () => {
    setIsRegenerating(true)
    await fetchInsights()
    setIsRegenerating(false)
    toast.success('Report regenerated')
  }

  if (loading) return <LoadingSkeleton />

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="font-fraunces text-3xl text-ink">Business Intelligence Report</h1>
          <p className="text-stone text-sm mt-1">
            Generated by ARIA · {new Date().toLocaleDateString('en-IN')}
          </p>
        </div>
        <button
          onClick={handleRegenerate}
          disabled={isRegenrating}
          className="flex items-center gap-2 px-4 py-2 bg-amber text-white rounded-lg hover:bg-opacity-90 disabled:opacity-50 transition font-medium"
        >
          <RotateCw size={18} />
          {isRegenrating ? 'Generating...' : 'Regenerate'}
        </button>
      </div>

      {insights && (
        <>
          {/* Executive Summary */}
          <div className="bg-cream-dark border-l-4 border-amber p-6 rounded-lg">
            <p className="text-xs text-amber uppercase font-mono font-semibold mb-2">
              Executive Summary
            </p>
            <p className="font-fraunces text-xl text-ink italic leading-relaxed">
              {insights.executive_summary}
            </p>
          </div>

          {/* Three Columns */}
          <div className="grid md:grid-cols-3 gap-6">
            {/* Risks */}
            <div>
              <h3 className="font-fraunces text-lg text-rust mb-4">⚠️ Risks</h3>
              <div className="space-y-3">
                {insights.risks && insights.risks.map((risk, idx) => (
                  <div key={idx} className="bg-rust-pale border-l-4 border-rust p-4 rounded-lg">
                    <p className="text-sm text-ink">{risk}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Opportunities */}
            <div>
              <h3 className="font-fraunces text-lg text-forest mb-4">↑ Opportunities</h3>
              <div className="space-y-3">
                {insights.opportunities && insights.opportunities.map((opp, idx) => (
                  <div key={idx} className="bg-forest-pale border-l-4 border-forest p-4 rounded-lg">
                    <p className="text-sm text-ink">{opp}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Actions */}
            <div>
              <h3 className="font-fraunces text-lg text-amber mb-4">→ Actions</h3>
              <div className="space-y-3">
                {insights.actions && insights.actions.map((action, idx) => (
                  <div key={idx} className="bg-amber-pale border-l-4 border-amber p-4 rounded-lg">
                    <p className="text-sm text-ink">{action}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Revenue Trend */}
          <SalesChart
            chartType="line"
            title="Revenue Trend — Last 30 Days"
            data={revenueData}
          />
        </>
      )}

      {!insights && (
        <div className="text-center py-12">
          <p className="text-stone">Loading insights...</p>
        </div>
      )}
    </div>
  )
}
